"""Context documents: what someone knows about a subject, written down.

Blitz files a question under a dot point by matching what the question says
against what a question about that dot point tends to say. For Physics that
knowledge is hand-written in `physics-lexicon.yaml`, and it is the single
biggest reason Physics tags well and a subject without one does not.

Writing that file for a new subject is a few hours with the study design
open — or twenty minutes with a model, which is what this module is for:

1. Blitz generates a **briefing questionnaire** for the subject, tailored
   to its real dot point ids: `briefing_text`.
2. The person gives that file and their study design to a model of their
   choice, which answers it.
3. They upload the model's answer back here as a **context document**. It is
   kept with the subject's material, and any concept lexicon inside it is
   validated against the study design and installed, so the next indexing
   run uses it.

A context document that carries no lexicon is still kept: it is the
subject's notes, and the next person to prepare material for it should read
it. Only the lexicon changes what the tagger does.
"""

from __future__ import annotations

import re
import shutil
from datetime import date
from pathlib import Path

import yaml

from . import config
from .corpus.sample import fingerprint
from .studydesign import StudyDesign, load_study_design

CONTEXT_DIRNAME = "context"
BRIEFING_SUFFIX = "-briefing-questions.md"
TEXTUAL = {".md", ".markdown", ".txt", ".yaml", ".yml", ".json"}
_FENCED = re.compile(r"```(?:ya?ml)?\s*\n(.*?)```", re.DOTALL | re.IGNORECASE)


def context_dir(subject_id: str, root: Path | None = None) -> Path:
    # Read through the module so a caller (or a test) that moves the folder
    # is honoured, rather than a path frozen at import.
    base = (Path(root) / "sources") if root else config.SOURCES_DIR
    return base / subject_id / CONTEXT_DIRNAME


def briefing_name(design: StudyDesign) -> str:
    return f"{design.subject_id}{BRIEFING_SUFFIX}"


# ---------------------------------------------------------------------------
# The questionnaire
# ---------------------------------------------------------------------------

def _dot_point_checklist(design: StudyDesign) -> str:
    out: list[str] = []
    for unit in design.units:
        for area in unit.areas_of_study:
            out.append(f"\n**Unit {unit.number}, Area of Study {area.number}: "
                       f"{area.title}**\n")
            for kk in area.key_knowledge:
                out.append(f"- `{kk.id}` — {kk.text}")
    return "\n".join(out)


def briefing_text(design: StudyDesign) -> str:
    """The questionnaire to hand to a model along with the study design."""
    n_kk = sum(len(a.key_knowledge) for a in design.all_areas())
    example = next((kk.id for a in design.all_areas() for kk in a.key_knowledge),
                   f"{design.subject_id}-u3-aos1-kk01")
    second = next((kk.id for a in design.all_areas()
                   for kk in a.key_knowledge if kk.id != example), example)
    types = ", ".join(f"`{qt.id}`" for qt in design.question_types) or "none defined"
    return f"""# Briefing questions — {design.subject_name}

_Generated by Blitz on {date.today():%d %b %Y} for study design fingerprint
`{fingerprint(design)}`._

## What to do with this file

Give **this file and the {design.subject_name} study design** to a capable
model (Claude, or whichever you use) and ask it to answer every question
below. Then save its answer and upload it back into Blitz as a context
document for {design.subject_name}. Blitz keeps the prose with the
subject's material and installs the YAML lexicon at the end, which is what
actually changes how questions are filed.

Nothing here leaves your machine unless you send it somewhere. The study
design is a public VCAA document; do not paste copyrighted textbook
content into a model as part of this.

## Why it matters

Blitz files each question under a dot point by matching the words the
question uses against the words a question about that dot point tends to
use. The study design does not supply those words. It says "apply the
field model to magnetic phenomena"; the exam says "a bar magnet is placed
between two current-carrying wires". Nothing useful overlaps, and what does
overlap actively misleads. The lexicon you are being asked to write is the
missing half.

## The subject

| | |
|---|---|
| subject | {design.subject_name} (`{design.subject_id}`) |
| accreditation | {design.accreditation or "not stated"} |
| dot points | {n_kk} |
| question type ids | {types} |

The {n_kk} dot point ids below are fixed. **Use them exactly as written.**
They are positional, so do not invent, reorder or renumber them.
{_dot_point_checklist(design)}

---

# Part A — questions to answer in prose

Answer these in your own words first. They are what a person preparing
material for this subject needs to know, and working through them is what
makes Part B accurate rather than generic.

## 1. How the subject is actually assessed

1. What forms do questions take in this subject: multiple choice, short
   answer, extended response, case study with a stimulus, calculation,
   data analysis, something else? Roughly what proportion of an exam is
   each?
2. What command terms does VCAA use in this subject (identify, outline,
   describe, explain, analyse, evaluate, justify, discuss, propose) and
   what does each actually require? Which ones signal a longer answer?
3. What is a typical mark allocation, and what does a 1-mark question look
   like next to a 6-mark one?
4. What stimulus material is common: a case study about a named business, a
   graph, a data table, a circuit diagram, a source extract, a photograph?
5. Is there anything in this subject that is not really a "question" but
   appears in textbooks and might be mistaken for one — worked examples,
   glossary boxes, chapter summaries, learning intentions?

## 2. How the study design breaks up

6. Which dot points are **content** and which are **skills** or
   investigation process? Skills dot points attract questions that are
   about method rather than topic, and they should only win when no
   content dot point fits.
7. Which dot points are routinely **examined together**, so a single
   question genuinely belongs to two of them?
8. Which dot points are **easily confused** with each other? For each such
   pair, what is the one word or phrase that tells them apart? This is the
   most valuable thing in this whole document.
9. Are any dot points **umbrella statements** that a question would rarely
   be filed under directly, because a more specific dot point always fits
   better?
10. Are any dot points effectively **never examined in writing** — a
    practical investigation requirement, say?

## 3. The vocabulary of each dot point

For **every one of the {n_kk} dot points**, answer:

11. What words and phrases does a question about it actually contain?
    Include: named laws, theories, models and people; named apparatus and
    materials; units and symbols; the everyday scenarios the subject uses
    to dress the concept up (a golf ball, a satellite, a family business, a
    named case study).
12. Which of those are **distinctive** — they appear in questions about
    this dot point and essentially nowhere else? Multi-word phrases are
    far better evidence than single words.
13. What words would **wrongly** pull a question towards this dot point?
    A question about braking distance is not about relativity because both
    mention "speed".
14. Is there a term that must **also** be present for a match to be real?
    For example, "field" alone means little; "magnetic field" is evidence.
15. Australian and British spellings, plurals, abbreviations and synonyms
    that a question might use instead.

## 4. Notation and extraction

16. What notation does this subject use that a PDF text extractor is likely
    to mangle: superscripts, subscripts, fractions, Greek letters, units
    with negative indices, currency, chemical formulae, equations?
17. Are there symbols or formats where the text is untrustworthy and the
    question is better shown as an image of the page?

---

# Part B — the lexicon, as YAML

End your answer with a single fenced `yaml` block in exactly this shape.
Blitz reads this block, checks every id against the study design and
installs it. Anything you write outside the block is kept as notes.

```yaml
subject_id: {design.subject_id}
dot_points:
  {example}:
    # Terms or phrases that indicate this dot point. A multi-word phrase
    # scores higher than a bare word, so prefer phrases. Lower case.
    triggers: [a distinctive phrase, another phrase, a named law, a unit]
    # Optional. If present, at least one of these must ALSO appear, which
    # stops a broad dot point claiming every question that shares one word.
    requires: [narrowing term]
    # Optional. Terms that rule this dot point out even if triggers matched.
    avoid: [a term that means a different dot point]
    # Optional, default 1.0. Breaks ties: a named phenomenon should beat
    # the generic apparatus it happens to use. Skills and investigation
    # dot points belong below 1.0 so they only win when nothing else fits.
    weight: 1.0
  {second}:
    triggers: [...]
```

Rules for the block:

- Every key under `dot_points` must be one of the {n_kk} ids listed above,
  copied exactly. Blitz rejects ids it does not recognise and tells the
  person which ones.
- Cover as many dot points as you can. A dot point with no entry falls back
  to word overlap with VCAA's own wording, which is weak.
- Aim for **five to fifteen triggers** per dot point. One or two is not
  enough to catch a real question; fifty will catch everything.
- Lower case throughout. Do not include the dot point's own study design
  wording as a trigger; questions do not use it.
- Use `avoid` generously for the confusable pairs you identified in
  question 8. Vetoes are what stop one popular dot point swallowing a whole
  chapter.

## How to check your work

Pick five real exam questions for this subject from memory. For each, read
only your triggers and decide which dot point it lands on. If a question
lands on two, add an `avoid` or a `requires` until it does not.
"""


# ---------------------------------------------------------------------------
# Storing what comes back
# ---------------------------------------------------------------------------

def find_lexicon(text: str) -> dict | None:
    """The lexicon inside a document, if it has one.

    Looks in fenced code blocks first, then at the whole document, so both
    a model's Markdown answer and a bare .yaml file work.
    """
    candidates = [m.group(1) for m in _FENCED.finditer(text)]
    candidates.append(text)
    for chunk in candidates:
        try:
            data = yaml.safe_load(chunk)
        except yaml.YAMLError:
            continue
        if isinstance(data, dict) and isinstance(data.get("dot_points"), dict):
            return data
    return None


def install_lexicon(subject_id: str, data: dict, root: Path | None = None,
                    design: StudyDesign | None = None) -> dict:
    """Validate a lexicon against the study design and write it.

    Ids the design does not have are dropped rather than written: they are
    almost always a lexicon built against a different version of the study
    design, and silently keeping them would file questions under dot points
    that have moved.
    """
    design = design or load_study_design(subject_id)
    valid = {kk.id for kk in design.all_key_knowledge()}
    entries = {k: v for k, v in (data.get("dot_points") or {}).items()}
    unknown = sorted(set(entries) - valid)
    kept = {k: v for k, v in entries.items() if k in valid}
    if not kept:
        raise ValueError(
            "none of the dot point ids in that lexicon belong to this study "
            f"design. It may have been written against a different version. "
            f"Unrecognised: {', '.join(unknown[:5])}"
            + (f" and {len(unknown) - 5} more" if len(unknown) > 5 else ""))

    out_dir = (Path(root) / "study-designs") if root else config.USER_DESIGN_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{subject_id}-lexicon.yaml"
    doc = {"subject_id": subject_id, "dot_points": kept}
    header = (
        f"# Concept lexicon for {design.subject_name}.\n"
        f"# Installed by Blitz on {date.today():%d %b %Y} from a context "
        f"document.\n"
        f"# Study design fingerprint {fingerprint(design)}.\n"
        f"# See blitz/ingest/lexicon.py for how triggers, requires, avoid and\n"
        f"# weight are scored.\n\n")
    path.write_text(header + yaml.safe_dump(doc, sort_keys=False,
                                            allow_unicode=True, width=100),
                    encoding="utf-8")

    from .ingest.lexicon import load_lexicon

    load_lexicon.cache_clear()
    return {"path": str(path), "dot_points": len(kept),
            "coverage": round(len(kept) / max(len(valid), 1), 2),
            "unknown": unknown}


def add_context(subject_id: str, uploads: list[tuple[str, bytes]],
                root: Path | None = None,
                design: StudyDesign | None = None) -> dict:
    """Store context documents and install any lexicon they carry."""
    design = design or load_study_design(subject_id)
    folder = context_dir(subject_id, root)
    folder.mkdir(parents=True, exist_ok=True)
    stored: list[str] = []
    lexicon: dict | None = None
    notes: list[str] = []

    for filename, blob in uploads:
        name = Path(filename).name or "context.md"
        suffix = Path(name).suffix.lower()
        if suffix not in TEXTUAL:
            notes.append(f"{name}: not a text document, skipped "
                         f"({', '.join(sorted(TEXTUAL))} are read)")
            continue
        dest = folder / name
        dest.write_bytes(blob)
        stored.append(name)
        if lexicon is not None:
            continue
        try:
            text = blob.decode("utf-8")
        except UnicodeDecodeError:
            notes.append(f"{name}: not valid UTF-8 text, kept but not read")
            continue
        found = find_lexicon(text)
        if found is not None:
            try:
                lexicon = install_lexicon(subject_id, found, root, design)
                lexicon["from"] = name
            except ValueError as exc:
                notes.append(f"{name}: {exc}")

    if not stored:
        raise ValueError("nothing was stored. " + (notes[0] if notes else
                                                   "No files were uploaded."))
    if lexicon is None and not notes:
        notes.append("No concept lexicon found in these documents, so they are "
                     "kept as notes and tagging is unchanged. The briefing "
                     "questions ask for one as a fenced yaml block.")
    return {"subject_id": subject_id, "folder": str(folder), "stored": stored,
            "lexicon": lexicon, "notes": notes}


def list_context(subject_id: str, root: Path | None = None) -> list[dict]:
    folder = context_dir(subject_id, root)
    if not folder.is_dir():
        return []
    return [{"name": p.name, "bytes": p.stat().st_size}
            for p in sorted(folder.iterdir()) if p.is_file()]


def remove_context(subject_id: str, name: str, root: Path | None = None) -> bool:
    """Delete one stored context document. The lexicon it installed stays."""
    folder = context_dir(subject_id, root).resolve()
    path = (folder / Path(name).name).resolve()
    if path.parent != folder or not path.is_file():
        return False
    path.unlink()
    return True


def clear_lexicon(subject_id: str, root: Path | None = None) -> bool:
    """Remove an installed lexicon, back to word-overlap tagging."""
    out_dir = (Path(root) / "study-designs") if root else config.USER_DESIGN_DIR
    path = out_dir / f"{subject_id}-lexicon.yaml"
    if not path.is_file():
        return False
    shutil.move(path, path.with_suffix(".yaml.removed"))
    from .ingest.lexicon import load_lexicon

    load_lexicon.cache_clear()
    return True
